<?php

// SI ON VEUT FAIRE DE LA POO
// AJOUTER UN AUTOLOAD DE CLASSE POUR CHARGER AUTOMATIQUEMENT LES CLASSES
// MAIS ON A LE PROBLEME DE LA POULE ET DE L'OEUF... 
// IL FAUT COMMENCER PAR UNE PREMIERE CLASSE
// ON VA RANGER TOUTES NOS CLASSES DANS LE DOSSIER php/class
// A LA MODE: LA PREMIERE CLASSE EST SOUVENT APPELEE App... 

// POUR COMMENCER, ON CHARGE LA PREMIERE CLASSE A MAIN AVEC require_once
require_once "php/class/App.php";

// MAINTENANT ON PEUT FAIRE DE LA POO
// LE PLUS SIMPLE, C'EST DE FAIRE DE LA PROGRAMMATION PAR CLASSE... 
App::start();


