<?php

// ICI ON VA RECEVOIR LES INFOS ENVOYEES EN AJAX PAR LE NAVIGATEUR

// ON VA RENVOYER AU NAVIGATEUR reponseServeur
$tabAsso = [];

// IL FAUT TRAITER LE FORMULAIRE ET STOCKER LES INFOS RECUES DANS UNE TABLE SQL
// TODO... 

// DEBUG
// ON RENVOIE AU NAVIGATEUR CE QU'IL NOUS A ENVOYE
$tabAsso["requete"] = $_REQUEST;

// EN PHP, ON PEUT CONVERTIR UN TABLEAU ASSOCIATIF EN JSON
$texteJSON = json_encode($tabAsso, JSON_PRETTY_PRINT);

// ENVOYER AU NAVIGATEUR
echo $texteJSON;