<?php


// ICI EN PHP, JE VAIS POUVOIR RECEVOIR LES INFORMATIONS ENVOYEES PAR LE NAVIGATEUR
// COMME LE NAVIGATEUR ENVOIE DES INFORMATIONS PAR PAIRES 
// nom=zakaria
// email=za@yahoo.fr
// ... 
// EN PHP, ON VA RETROUVER CES INFORMATIONS DANS UN TABLEAU ASSOCIATIF

// PHP CREE ET REMPLIT UN TABLEAU ASSOCIATIF POUR NOUS
// ET ON A JUSTE A ALLER CHERCHER LES BONNES INFORMATIONS

// ON AFFICHE LE CONTENU DU TABLEAU ASSOCIATIF $_REQUEST
print_r($_REQUEST);

// SI JE VEUX ACCEDER AU NOM DANS LE TABLEAU ASSOCIATIF
$nom        = $_REQUEST["nom"];
$email      = $_REQUEST["email"];
$message    = $_REQUEST["message"];

echo "<h3>$nom VIENT DE LAISSER UN MESSAGE AVEC $email ET IL A ECRIT $message</h3>";

