const mangas = [
  "One Punch-Man",
  "Beastars",
  "Eveil",
  "My Home Hero",
  "Le Voleur d'estampes",
  "Jagaaan",
  "Atrail",
  "The Way of the Househusband",
  "Komi Can't Communicate",
  "My Hero Academia",
  "Samurai 8",
  "For the Kid I Saw in My Dream",
  "I Want To Eat Your Pancreas",
  "Nyankees",
  "Our Dreams At Dusk",
  "Skull-face Bookseller Honda-san",
  "Fullmetal Alchemist",
];
